Feature/flag sets
splitio/python-client pull request #486
Opened 2023-11-01 20:53 UTC by chillaq

# Python SDK

## What did you accomplish?

## How do we test the changes introduced in this PR?

## Extra Notes

2023-11-01 21:10 UTC, mmelograno requested changes

2023-11-01 21:10 UTC, mmelograno commented on CHANGES.txt
> +9.6.1 (Nov 3, 2023)
9.6.0

2023-11-01 21:14 UTC, chillaq commented on CHANGES.txt
> +9.6.1 (Nov 3, 2023)
fixed

2023-11-01 21:20 UTC, mmelograno requested changes

2023-11-01 21:20 UTC, mmelograno commented on splitio/client/config.py
> +import re
this import is not needed

2023-11-01 21:20 UTC, mmelograno commented on splitio/storage/__init__.py
> +import threading
unused

2023-11-01 21:20 UTC, mmelograno commented on splitio/util/storage_helper.py
> +def combine_valid_flag_sets(result_sets):
same as def combine_valid_flag_sets(result_sets):
duplicated code

2023-11-02 02:26 UTC, mmelograno approved these changes

2023-11-02 03:00 UTC, chillaq commented on splitio/storage/__init__.py
> +import threading
fixed

2023-11-02 03:00 UTC, chillaq commented on splitio/util/storage_helper.py
> +def combine_valid_flag_sets(result_sets):
fixed

2023-11-02 03:00 UTC, chillaq commented on splitio/client/config.py
> +import re
fixed

2023-11-02 03:00 UTC, merged